export const GET_USER = 'GET_USER'
export const GET_TOKEN = 'GET_TOKEN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const PROFILE_USER = 'PROFILE_USER'